export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './Login',
      },
      {
        component: './404',
      },
    ],
  },
  {
    name: '工作台',
    icon: 'smile',
    path: '/workspace',
    component: './Workspace',
    access: 'normalRouteFilter',
    auth: 'workspace',
  },
  {
    name: '权限配置',
    icon: 'control',
    path: '/permission-config',
    component: './PermissionConfig',
  },
  {
    name: '基础信息管理',
    icon: 'table',
    path: '/base',
    access: 'normalRouteFilter',
    auth: 'base',
    routes: [
      {
        name: '部门管理',
        path: '/base/department',
        component: './DepartmentManage',
        access: 'normalRouteFilter',
        auth: 'base.department',
      },
      {
        name: '员工管理',
        path: '/base/user',
        component: './UserManage',
        access: 'normalRouteFilter',
        auth: 'base.user',
      },
      {
        name: '新增员工',
        path: '/base/user/add',
        component: './UserManage/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'base.user',
      },
      {
        name: '角色管理',
        path: '/base/role',
        component: './RoleManage',
        access: 'normalRouteFilter',
        auth: 'base.role',
      },
      {
        name: '菜单管理',
        path: '/base/resource',
        component: './ResourceManage',
        access: 'normalRouteFilter',
        auth: 'base.resource',
      },
      {
        name: '权限管理',
        path: '/base/auth',
        component: './AuthManage',
        access: 'normalRouteFilter',
        auth: 'base.auth',
      },
      {
        name: '产品品牌管理',
        path: '/base/brand',
        component: './BrandManage',
        access: 'normalRouteFilter',
        auth: 'base.brand',
      },
      {
        name: '产品管理',
        path: '/base/product',
        component: './ProductManage',
        access: 'normalRouteFilter',
        auth: 'base.product',
      },
      {
        name: '客户管理',
        path: '/base/customer',
        component: './CustomerManage',
        access: 'normalRouteFilter',
        auth: 'base.customer',
      },
      {
        name: '新增客户',
        path: '/base/customer/add',
        component: './CustomerManage/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'base.customer',
      },
      {
        name: '费用类型管理',
        path: '/base/costType',
        component: './CostTypeManage',
        access: 'normalRouteFilter',
        auth: 'base.costType',
      },
      {
        component: './404',
      },
    ],
  },
  {
    name: '订单管理',
    icon: 'table',
    path: '/order',
    access: 'normalRouteFilter',
    auth: 'order',
    routes: [
      {
        name: '销售订单',
        path: '/order/sale',
        component: './OrderSale',
        access: 'normalRouteFilter',
        auth: 'order.sale',
      },
      {
        name: '新增销售订单',
        path: '/order/sale/add',
        component: './OrderSale/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'order.sale',
      },
      {
        name: '采购订单',
        path: '/order/purchase',
        component: './OrderPurchase',
        access: 'normalRouteFilter',
        auth: 'order.purchase',
      },
      {
        name: '新增采购订单',
        path: '/order/purchase/add',
        component: './OrderPurchase/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'order.purchase',
      },
    ],
  },
  {
    name: '销售管理',
    icon: 'table',
    path: '/sale',
    access: 'normalRouteFilter',
    auth: 'sale',
    routes: [
      {
        name: '销售出库单',
        path: '/sale/storage',
        component: './SaleStorage',
        access: 'normalRouteFilter',
        auth: 'sale.storage',
      },
      {
        name: '新增销售出库单',
        path: '/sale/storage/add',
        component: './SaleStorage/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'sale.storage',
      },
      {
        name: '销售退库单',
        path: '/sale/retrieval',
        component: './SaleRetrieval',
        access: 'normalRouteFilter',
        auth: 'sale.retrieval',
      },
      {
        name: '新增销售退库单',
        path: '/sale/retrieval/add',
        component: './SaleRetrieval/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'sale.retrieval',
      },
    ],
  },
  {
    name: '库存管理',
    icon: 'table',
    path: '/stock',
    access: 'normalRouteFilter',
    auth: 'stock',
    routes: [
      {
        name: '采购入库单',
        path: '/stock/storage',
        component: './PurchaseStorage',
        access: 'normalRouteFilter',
        auth: 'stock.storage',
      },
      {
        name: '新增采购入库单',
        path: '/stock/storage/add',
        component: './PurchaseStorage/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'stock.storage',
      },
      {
        name: '采购退库单',
        path: '/stock/retrieval',
        component: './PurchaseRetrieval',
        access: 'normalRouteFilter',
        auth: 'stock.retrieval',
      },
      {
        name: '新增采购退库单',
        path: '/stock/retrieval/add',
        component: './PurchaseRetrieval/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'stock.retrieval',
      },
      {
        name: '库存明细表',
        path: '/stock/details',
        component: './StockDetails',
        access: 'normalRouteFilter',
        auth: 'stock.details',
      },
    ],
  },
  {
    name: '财务管理',
    icon: 'table',
    path: '/bills',
    access: 'normalRouteFilter',
    auth: 'bills',
    routes: [
      {
        name: '收付款记录管理',
        path: '/bills/paymentRecord',
        component: './PaymentRecord',
        access: 'normalRouteFilter',
        auth: 'bills.paymentRecord',
      },
      {
        name: '新增收付款记录',
        path: '/bills/paymentRecord/add',
        component: './PaymentRecord/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'bills.paymentRecord',
      },
      {
        name: '待收待付款明细',
        path: '/bills/prepayment',
        component: './PrepaymentDetails',
        access: 'normalRouteFilter',
        auth: 'bills.prepayment',
      },
      {
        name: '发票管理',
        path: '/bills/invoice',
        component: './InvoiceManage',
        access: 'normalRouteFilter',
        auth: 'bills.invoice',
      },
      {
        name: '新增发票',
        path: '/bills/invoice/add',
        component: './InvoiceManage/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'bills.invoice',
      },
    ],
  },
  {
    name: '日常管理',
    icon: 'table',
    path: '/daily',
    access: 'normalRouteFilter',
    auth: 'daily',
    routes: [
      {
        name: '费用报销管理',
        path: '/daily/costApply',
        component: './CostApplyManage',
        access: 'normalRouteFilter',
        auth: 'daily.costApply',
      },
      {
        name: '新增费用报销',
        path: '/daily/costApply/add',
        component: './CostApplyManage/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'daily.costApply',
      },
    ],
  },
  {
    name: '询价管理',
    icon: 'table',
    path: '/inquiry',
    access: 'normalRouteFilter',
    auth: 'inquiry',
    routes: [
      {
        name: '询价管理',
        path: '/inquiry',
        component: './InquiryManage',
        access: 'normalRouteFilter',
        auth: 'inquiry',
      },
      {
        name: '新增询价',
        path: '/inquiry/add',
        component: './InquiryManage/Add',
        hideInMenu: true,
        access: 'normalRouteFilter',
        auth: 'inquiry',
      },
    ],
  },
  {
    path: '/',
    redirect: '/workspace',
  },
  {
    component: './404',
  },
];
